from pathlib import Path

widget = Path("xDrip Watch Complication/XDripWatchComplication.swift")
s = widget.read_text(encoding="utf-8")
old = '''        .configurationDisplayName("xDrip Graph")\n        .description("xDrip 2-hour glucose graph")\n        .supportedFamilies([.accessoryRectangular])'''
new = '''        .configurationDisplayName("xDrip")\n        .description("Glucose graph or compact glucose status")\n        .supportedFamilies([.accessoryRectangular, .accessoryCircular])'''
if s.count(old) != 1:
    raise RuntimeError(f"Build35: expected exactly one Build34 widget registration block, found {s.count(old)}")
widget.write_text(s.replace(old, new, 1), encoding="utf-8")

circular = Path("xDrip Watch Complication/Views/AccessoryCircularView.swift")
circular.write_text('''//\n//  AccessoryCircularView.swift\n//  xDrip Watch Complication Extension\n//\n//  Build 35: compact circular glucose status for Apple Watch.\n//\n\nimport Foundation\nimport SwiftUI\n\nextension XDripWatchComplication.EntryView {\n    @ViewBuilder\n    var accessoryCircularView: some View {\n        if entry.widgetState.keepAliveIsDisabled {\n            Image(systemName: "exclamationmark.triangle.fill")\n                .font(.title2)\n                .foregroundStyle(.colorPrimary)\n                .widgetBackground(backgroundView: Color.clear)\n        } else {\n            let displayColor = entry.widgetState.bgTextColor()\n            let glucoseText = entry.widgetState.bgValueStringInUserChosenUnit()\n            let trendArrow = entry.widgetState.trendArrow()\n            let deltaText = entry.widgetState.deltaChangeStringInUserChosenUnit()\n            let readingTime = entry.widgetState.bgReadingDate?.formatted(date: .omitted, time: .shortened) ?? "--:--"\n\n            VStack(spacing: entry.widgetState.isSmallScreen() ? -1 : 0) {\n                HStack(alignment: .firstTextBaseline, spacing: 2) {\n                    Text(glucoseText)\n                        .font(.system(size: entry.widgetState.isSmallScreen() ? 17 : 20, weight: .bold))\n                        .foregroundStyle(displayColor)\n                        .minimumScaleFactor(0.55)\n                        .lineLimit(1)\n                        .monospacedDigit()\n\n                    Text(trendArrow)\n                        .font(.system(size: entry.widgetState.isSmallScreen() ? 15 : 18, weight: .bold))\n                        .foregroundStyle(displayColor)\n                        .minimumScaleFactor(0.6)\n                        .lineLimit(1)\n                }\n                .frame(maxWidth: .infinity, alignment: .center)\n\n                Text(deltaText.isEmpty ? " " : deltaText)\n                    .font(.system(size: entry.widgetState.isSmallScreen() ? 9 : 11, weight: .semibold))\n                    .foregroundStyle(entry.widgetState.hasRecentReading ? Color.colorPrimary : Color.gray)\n                    .lineLimit(1)\n                    .monospacedDigit()\n\n                Text(readingTime)\n                    .font(.system(size: entry.widgetState.isSmallScreen() ? 8 : 10, weight: .semibold))\n                    .foregroundStyle(entry.widgetState.bgReadingDate == nil ? Color.gray : Color.colorPrimary)\n                    .lineLimit(1)\n                    .monospacedDigit()\n            }\n            .frame(maxWidth: .infinity, maxHeight: .infinity, alignment: .center)\n            .widgetBackground(backgroundView: Color.clear)\n        }\n    }\n}\n''', encoding="utf-8")

print("Build 35 circular glucose complication layout applied successfully.")
